services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: always
    ports:
      - 8888:80
    volumes:
      - ./src/:/var/www/
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - phpmyadmin_data:/var/www/html/:ro
    depends_on:
      - php
      - mysql
      - phpmyadmin
    networks:
      - taura_api

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: tauradb
      MYSQL_USER: taura
      MYSQL_PASSWORD: 3917
      MYSQL_ROOT_PASSWORD: 3917
    ports:
      - 3308:3308
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - taura_api

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    # restart: always
    ports:
      - "3400:80"
    environment:
      PMA_HOST: mysql
      # MYSQL_USER: taura
      # MYSQL_PASSWORD: 3917
    networks:
      - taura_api
    depends_on:
      - mysql
    #links:
    #  - db

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./src/:/var/www/
    ports:
      - 9000:80
    networks:
      - taura_api

volumes:
  mysql_data:
  phpmyadmin_data:

networks:
  taura_api:
