services:
  # NGINX Service
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - 8888:80
    volumes:
      - ./src:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - phpmyadmin_data:/var/www/html/:ro
    depends_on:
      - php
      - db
      - phpmyadmin
    networks:
      - net_api
  # Database Service
  db:
    image: mysql:5.7
    ports:
      - 3308:3308
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - net_api

  # PHPMyAdmin Service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "3400:80"
    environment:
      PMA_HOST: db
    depends_on:
      - db
    networks:
      - net_api
    #links:
    #  - db
  # PHP Service
  php:
    build:
      context: .
      target: php
      args:
        - APP_ENV=${APP_ENV}
    environment:
      - APP_ENV=${APP_ENV}
      - CONTAINER_ROLE=app
    working_dir: /var/www
    volumes:
      - ./src:/var/www
    ports:
      - 9000:80
    depends_on:
      - db

volumes:
  db_data:
  phpmyadmin_data:

networks:
  net_api:
